rewwq

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -538,7 +538,6 @@
 #     jobs:
 #       - dependency_check
 
-
 version: 2.1
 
 jobs:
@@ -575,7 +574,7 @@ jobs:
 
             # Fetch the latest version from GitHub API
             LATEST_VERSION=$(curl -s https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest | jq -r .tag_name)
-            # Remove "v" prefix
+            # Remove "v" prefix if present
             LATEST_VERSION=${LATEST_VERSION#v}
             echo "Latest Dependency-Check version from GitHub: $LATEST_VERSION"
 
@@ -591,13 +590,21 @@ jobs:
       - run:
           name: Install Dependency-Check
           command: |
-            wget "https://github.com/jeremylong/DependencyCheck/releases/download/v${LATEST_VERSION}/dependency-check-${LATEST_VERSION}-release.zip"
-            unzip dependency-check-${LATEST_VERSION}-release.zip
-            rm dependency-check-${LATEST_VERSION}-release.zip
-            cd /$HOME/project/dependency-check/bin
+            if [ -n "$LATEST_VERSION" ]; then
+              echo "Downloading Dependency-Check version $LATEST_VERSION"
+              wget "https://github.com/jeremylong/DependencyCheck/releases/download/v${LATEST_VERSION}/dependency-check-${LATEST_VERSION}-release.zip" -O dependency-check-${LATEST_VERSION}-release.zip
+              unzip dependency-check-${LATEST_VERSION}-release.zip
+              rm dependency-check-${LATEST_VERSION}-release.zip
+              cd dependency-check
+              echo "Successfully installed Dependency-Check version $LATEST_VERSION."
+            else
+              echo "LATEST_VERSION is empty, cannot download Dependency-Check."
+              exit 1
+            fi
+
             # Store the new version locally and upload it to S3 for future runs
-            echo $LATEST_VERSION > .dependency-check-version
-            aws s3 cp .dependency-check-version s3://$S3_BUCKET/$VERSION_FILE
+            echo $LATEST_VERSION > $LOCAL_VERSION_FILE
+            aws s3 cp $LOCAL_VERSION_FILE s3://$S3_BUCKET/$VERSION_FILE
 
       # Run Dependency-Check update only (no scan)
       - run:
@@ -610,8 +617,7 @@ jobs:
       - run:
           name: Upload ODC Data to S3
           command: |
-            aws s3 sync /tmp/owasp-data s3://newbucketbusola/owasp-data --delete
-
+            aws s3 sync /tmp/owasp-data s3://$S3_BUCKET/owasp-data --delete
 
 
 workflows:
